{{- $fluxSettingsDependencytrack := merge .Values.dependencytrack.flux .Values.flux -}}
{{- if .Values.dependencytrack.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dependencytrack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dependencytrack
    app.kubernetes.io/component: "security"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: dependencytrack
  chart:
    spec:
      chart: {{ .Values.dependencytrack.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: dependency-track
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsDependencytrack | nindent 2 }}
  
  {{- if .Values.dependencytrack.postRenderers }}
  postRenderers:
  {{ toYaml .Values.dependencytrack.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-dependencytrack-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-dependencytrack-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-dependencytrack-values
      kind: Secret
      valuesKey: "overlays"

  dependsOn:
    - name: bigbang
      namespace: {{ .Release.Namespace }}
{{- end }}
