{{- $fluxSettingsBigBang := merge .Values.bigbang.flux .Values.flux -}}
{{- if .Values.bigbang.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bigbang
  namespace: {{ .Release.Namespace }}
spec:
  releaseName: bigbang
  targetNamespace: bigbang
  chart:
    spec:
      chart: {{ .Values.bigbang.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: bigbang
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsBigBang | nindent 2 }}

  {{- if .Values.bigbang.postRenderers }}
  postRenderers:
  {{ toYaml .Values.bigbang.postRenderers | nindent 4 }}
  {{- end }}

  valuesFrom:
    - name: {{ .Release.Name }}-bigbang-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-bigbang-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-bigbang-values
      kind: Secret
      valuesKey: "overlays"

{{- end }}